[project]
name = "caballus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django-environ>=0.11.2",
    "django>=5.1.2",
    "psycopg2-binary>=2.9.10",
]
