version: '3.8'

services:
  caballus:
    build: ./caballus
    expose:
      - "8000"
  # Run server
    entrypoint: ["/bin/bash", "./scripts/caballus.sh"]
    volumes:
      - ./caballus:/caballus
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:16.1
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
